#!/bin/bash
{
exec < date      # stdin replaced by file "data-file"
lines=0
while read line; do {
  echo $line | tr 'a-z' 'A-Z'   #change letters all to upper case
  ((lines++));   # this is the only correct format to do a i++
}
done
echo lines is equal to $lines

echo "***********************"
echo "The following part is the same as above"
echo "***********************"
cat date | while read line; do {
            echo $line
           }
          done

echo "***********************"
echo "The following part is the same as above"
echo "***********************"
lines=0
while read line; do {
  echo $line
  let lines=lines+1
  let "lines += 1"    #above two lines are the same
}
done < date
echo $lines

if [ -e date ]; then
  read firstLine
  echo $firstLine
fi < date
} > try         # Redirects output of everything in block to file try.

echo "***********************"
echo "The following part is the same as above"
echo "***********************"
IFS=$'\n'      # make newlines the only separator, otherwise it will be a space
for line in $(cat date); do
  echo $line
done
exit 0
