#!/bin/bash
#It's OK to have a line have multiple assignments
var1=21  var2=22  var3=$V3
echo
echo "var1=$var1   var2=$var2   var3=$var3"

usage() {
          echo "$0 Usage: "
          echo "haha"
          echo "hoho"
          exit 1
}
